# Generated by Django 3.0.8 on 2020-07-19 14:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200719_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/accounts_pics'), upload_to='', verbose_name='profilePic'),
        ),
    ]
