# Generated by Django 3.0.8 on 2020-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200719_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts_pics', verbose_name='profilePic'),
        ),
    ]
